#!/bin/bash
echo "DomainFlow Go Backend Environment Setup Guide"
echo "---------------------------------------------"
echo "1. Go Installation:"
echo "   Ensure Go (version 1.19 or later) is installed and configured in your PATH."
echo "   Verify with: go version"
echo ""
echo "2. Environment Variables (Recommended for Production):"
echo "   It's best to set sensitive information like API keys via environment variables."
echo "   You can set these in your shell profile (e.g., ~/.bashrc, ~/.zshrc) or an .env file"
echo "   (if your deployment method supports it, e.g., Docker with --env-file)."
echo ""
echo "   Example variables to set:"
echo "   export DOMAINFLOW_PORT=\"8080\"  # Default is 8080"
echo "   export DOMAINFLOW_API_KEY='a-very-secure-random-string-generated-for-production'"
echo ""
echo "   After adding to your profile, source it: source ~/.bashrc (or your profile file)"
echo ""
echo "3. Configuration File (config.json):"
echo "   The server loads settings from 'config.json' in the 'backend' directory."
echo "   - If 'config.json' is not found, it attempts to copy from 'config.example.json'."
echo "   - If neither exists, it uses hardcoded defaults (which is not recommended for API keys)."
echo "   - Environment variables (DOMAINFLOW_PORT, DOMAINFLOW_API_KEY) override 'config.json' settings."
echo ""
echo "   Review and customize 'config.example.json' and then copy it:"
echo "   cd backend"
echo "   cp config.example.json config.json"
echo "   nano config.json  # Edit as needed"
echo ""
echo "4. Building and Running:"
echo "   Navigate to the 'backend' directory:"
echo "   cd path/to/domainflow/backend"
echo ""
echo "   Fetch dependencies:"
echo "   go mod tidy"
echo ""
echo "   Build the server:"
echo "   ./scripts/build.sh"
echo ""
echo "   Run the server:"
echo "   ./scripts/run.sh"
echo ""
echo "Setup complete. Refer to backend/README.md for more details on API usage."
